%Plot the results of similation
%%
%Print the results
close all;
faultStr = 'Offset_fault';
figPath = [pwd '\Figures'];

%simObj must be obtained for simulation - multiple scenarios
%SimObj generated by fault simulation. 
%Plot the residual evaluated
%The fault k means that all sensors has faults except k
obsRes = out;
% simObj = out;
numObs = p;
uncertType = 2;
uncertFreq = 100; %10ms%
fminVec = {0.1*Cxe(1),0.1*Cxe(2),0.1*Cxe(3)};
alphaVec{p} = [];
jthVec{p} = [];
for i = 1:p
    alphaVec{i} = getalpha(obsSys{i}.params.gamma,...
        obsSys{i}.dfbound,obsSys{2}.params.theta_a_bar,...
        obsSys{i}.params.theta_x_bar,omega,obsSys{i}.params.betabar,fminVec{i});
    jthVec{i} = getthreshold(obsSys{i}.params.gamma,...
        obsSys{i}.dfbound,obsSys{i}.params.theta_a_bar,obsSys{i}.params.theta_x_bar,omega,alphaVec{i});
end


%uncertFreq out.ucertFreq;
hJArray{size(simObj,1),size(simObj,1)} = [];
pJArray{size(simObj,1),size(simObj,2)} = [];
axJArray{size(simObj,1),size(simObj,2)} = [];

%Plot only
for i = 1:size(simObj,1)
    for j = 1:size(simObj,2)
        [hJArray{i,j},pJArray{i,j},axJArray{i,j}] = plotresidual(simObj{i,j},jthVec);
        setpaperfigsize(hJArray{i,j},6.0);
    end
end
%% Save all figures
for i = 1:size(simObj,1)
    for j = 1:size(simObj,2)
        savesimfigs(hJArray{i,j},'figname',[hJArray{i,j}.Name],...
            'figfolder',fullfile(figPath),...
            'formatsFolders',{'JPG','FIG','PDF','EPS'},...
            'figformats',{'jpg','fig','pdf','eps'});
    end
end
%%
%New Jth2
alphaVec2 = alphaVec;
newjthVec = jthVec;
alphaVec2{2} = 0.0036;
alphaVec2{3} = 0.0068;
for i = 2:3
    newjthVec{i} = getthreshold(obsSys{i}.params.gamma,...
        obsSys{i}.dfbound,obsSys{i}.params.theta_a_bar,obsSys{i}.params.theta_x_bar,omega,alphaVec2{i});
end

[hJ2,pJ2,axJ2] = plotresidual(simObj{1,2},newjthVec);
setpaperfigsize(hJ2,6);
[hJ3,pJ3,axJ3] = plotresidual(simObj{1,3},newjthVec);
setpaperfigsize(hJ3,6);
%%
savesimfigs(hJ2,'figname',['new' hJ2.Name],...
            'figfolder',fullfile(figPath),...
            'formatsFolders',{'JPG','FIG','PDF','EPS'},...
            'figformats',{'jpg','fig','pdf','eps'});
savesimfigs(hJ3,'figname',['new' hJ3.Name],...
            'figfolder',fullfile(figPath),...
            'formatsFolders',{'JPG','FIG','PDF','EPS'},...
            'figformats',{'jpg','fig','pdf','eps'});
% %%
% [hJ1,pJ1,axJ1] = plotresidual(simObj{2,2},jthVec);
% %%
% savesimfigs(hJ1,'figname',[hJ1.Name],...
%     'figfolder',fullfile(figPath),...
%     'formatsFolders',{'JPG','FIG','PDF','EPS'},...
%     'figformats',{'jpg','fig','pdf','eps'});
% %%
% [hJ2,pJ2,axJ2] = plotresidual(out2,jthVec,sNum,fType);
% zommJ2Xlim = [0.19 0.21];
% zoomJ2Ylim = [0 2];
%     %     %All axis or specific plot
% %axZoomJ2 = plotZoom(hJ2,zommJ2Xlim,zoomJ2Ylim);
% lJ2 = legend(axJ2,'Location','northwest');
% 
% %%
% savesimfigs(hJ2,'figname',[hJ2.Name],...
%     'figfolder',fullfile(figPath),...
%     'formatsFolders',{'JPG','FIG','PDF','EPS'},...
%     'figformats',{'jpg','fig','pdf','eps'});
% 
% %%
% fType  = 'full'; %uncertainties and df;
% [hJ3,pJ3,axJ3] = plotresidual(out3,jthVec,sNum,fType);
% zommJ3Xlim = [0.19 0.21];
% zoomJ3Ylim = [0 2];
% %axZoomJ2 = plotZoom(hJ3,zommJ3Xlim,zoomJ3Ylim);
% lJ3 = legend(axJ3,'Location','northwest');
% %%
% savesimfigs(hJ3,'figname',[hJ3.Name],...
%     'figfolder',fullfile(figPath),...
%     'formatsFolders',{'JPG','FIG','PDF','EPS'},...
%     'figformats',{'jpg','fig','pdf','eps'});
% %%
% sNum = 1;
% uncertType = 2;
% %%
% fType  = 'single'; %uncertainties and df;
% [hJf1,pJf1,axJf1] = plotresidual(outf1,jthVec,sNum,fType);
% %%
% savesimfigs(hJf1,'figname',[hJf1.Name],...
%     'figfolder',fullfile(figPath),...
%     'formatsFolders',{'JPG','FIG','PDF','EPS'},...
%     'figformats',{'jpg','fig','pdf','eps'});
% %%
% sNum = 2;%%
% fType  = 'single'; %uncertainties and df;
% [hJf2,pJf2,axJf2] = plotresidual(outf2,jthVec,sNum,fType);
% zommJf2Xlim = [0.19 0.21];
% zoomJf2Ylim = [0 2];
%     %     %All axis or specific plot
% %axZoomJ2 = plotZoom(hJ2,zommJ2Xlim,zoomJ2Ylim);
% lJf2 = legend(axJf2,'Location','northwest');
% 
% %%
% savesimfigs(hJf2,'figname',[hJf2.Name],...
%     'figfolder',fullfile(figPath),...
%     'formatsFolders',{'JPG','FIG','PDF','EPS'},...
%     'figformats',{'jpg','fig','pdf','eps'});
% 
% %%
% sNum = 3;
% fType  = 'single'; %uncertainties and df;
% [hJf3,pJf3,axJf3] = plotresidual(out3,jthVec,sNum,fType);
% zommJ3Xlim = [0.19 0.21];
% zoomJ3Ylim = [0 2];
% %axZoomJ2 = plotZoom(hJ3,zommJ3Xlim,zoomJ3Ylim);
% lJf3 = legend(axJf3,'Location','northwest');
% %%
% savesimfigs(hJf3,'figname',[hJf3.Name],...
%     'figfolder',fullfile(figPath),...
%     'formatsFolders',{'JPG','FIG','PDF','EPS'},...
%     'figformats',{'jpg','fig','pdf','eps'});
% 
% 
